export {
  findTerminalBufferMatch,
  readTerminalBufferText,
  readTerminalCellHeight,
  readTerminalCellSize,
  readTerminalCursor,
  readTerminalDims,
  readTerminalViewportY,
  registerTerminalInstance,
  scrollTerminalLines,
  focusRegisteredTerminal,
  pasteIntoRegisteredTerminal,
  sendTerminalVirtualKey,
  setTerminalVirtualModifier,
  unregisterTerminalInstance,
} from "./panels/terminal-instance-registry.js"
